# Generated by Django 5.0.7 on 2024-07-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("artist", models.CharField(max_length=100)),
                ("duration", models.IntegerField()),
                ("thumbnail", models.ImageField(upload_to="images/")),
                ("file", models.FileField(upload_to="music/")),
            ],
        ),
    ]
